### ISSUE TITLE
how can i turn off the esp32 even if the battery is present?

### ISSUE THREAD

**Issue by carminelau** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#105]
how can i turn off the esp32 even if the battery is present? I would like to let the ESP32 rest for 15 minutes twice a day

I use a timer to not power the esp32 but when the electric current is off, the battery is used and therefore the ESP32 does not turn off

**Comment by Mr-HaleYa** [comment]
Use the esp32 deep sleep function 
Just look it up On google

**Comment by Mr-HaleYa** [comment]
@carminelau @lewisxhe this should be closed
