### ISSUE TITLE
Need info on a Board component

### ISSUE THREAD

**Issue by ishdemon** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#107]
@lewisxhe one of the component probably a capacitor got damaged . Can you tell me which component is that so i can replace it. Although the board is working fine with no issues so far without that component.

![IMG_20210412_212902__01__01](https://user-images.githubusercontent.com/13925683/114427973-430bfe00-9bd9-11eb-8b50-3e86da7aefb3.jpg)

**Comment by Mr-HaleYa** [comment]
![image](https://user-images.githubusercontent.com/42821995/117369937-e1128180-ae82-11eb-90e7-fba768377c76.png)
this is your part and it helps stabilize the 3.3 out of that IC (ME6217) that is used for GPS antenna, it'll be just fine without it 

if this solved your issue please close
