### ISSUE TITLE
Not able to use GPS & Network simultaneously

### ISSUE THREAD

**Issue by ishdemon** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#108]
When you call `modem.getGPS` and if you are connected to internet, it disconnects the network. Can we use GPS and GPRS together without losing connection in this board?
https://github.com/vshymanskyy/TinyGSM/issues/143

**Comment by Mr-HaleYa** [comment]
Of course it is, why wouldn't you be able to? 
Instead of asking pointless questions try it yourself

**Comment by ishdemon** [comment]
i did as mentioned in this comment. It disconnects the network.That's why i asked if there is any other way someone knows.

> When you call `modem.getGPS` and if you are connected to internet, it disconnects the network. Can we use GPS and GPRS together without losing connection in this board?

**Comment by ishdemon** [comment]
Simcom's onboard GPS is shit...
