### ISSUE TITLE
Unable to flash device

### ISSUE THREAD

**Issue by Ollebolle** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#117]
Hi! I just got this board and it looks awesome, but I'm not able to flash it at all. I've tried the platformio example as well as simply going through the Arduino IDE but no matter what I do I get this error message: 

```
Chip is ESP32D0WDQ5 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
MAC: ****
Uploading stub...

A fatal error occurred: Failed to write to target RAM (result was 01070000)
*** [upload] Error 2
```

I've also tried 3 different usb-c cables with no difference. I've also set a bridge in between pin0 to ground and thereafter reset the board, which gives me: 
```
rst:0x1 (POWERON_RESET),boot:0x3 (DOWNLOAD_BOOT(UART0/UART1/SDIO_REI_REO_V2))
waiting for download
```

But still not able to flash. Can anyone please help? 🤔

**Comment by francoisfanuel** [comment]
I have the same problem using Big Sur. I switched to platformio remote on a raspi 4 to workaround it until I figure it out.

**Comment by Mr-HaleYa** [comment]
yup mac sucks for Arduino development. Use a Windows PC, downgrade the OS, or find another hobby... not much you can do until they fix the bug

**Comment by Ollebolle** [comment]
> yup mac sucks for Arduino development. Use a Windows PC, downgrade the OS, or find another hobby... not much you can do until they fix the bug

Yeh I eventually gave up trying to get it to work on Mac and moved over to my Windows machine where it worked right away. 🤷‍♂️
