### ISSUE TITLE
mqtt publish problem

### ISSUE THREAD

**Issue by crash007** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#13]
Hi,
can someone verify mqtt publish works with either DFRobot or TinyGSM?
Im unable to publish with both.

I can connect to host but when doing publish nothing happens. 
Im using GRPS mode and not NB.

from the server log:
1583473025: New connection from xx.xx.xx.xx on port 1883.
1583473025: New client connected from xx.xx.xx as T-Call-1 (p2, c1, k15, xxxx').
1583473025: No will message specified.
1583473025: Sending CONNACK to T-Call-1 (0, 0)
1583473047: Client T-Call-1 has exceeded timeout, disconnecting.

**Comment by lewisxhe** [comment]
You can check out another warehouse with usage examples of TinyGSM and Cayenne.
https://github.com/Xinyuan-LilyGO/LilyGO-SIM7000-Cayenne

**Comment by crash007** [comment]
Thanks I will check it out. So far I have tried with DFRobot ,TinyGSM and
Fona

Den ons 11 mars 2020 kl 15:43 skrev lewis he <notifications@github.com>:

**Comment by crash007** [comment]
The problem was my mobile subscription. 
Can verify the mqtt examples work
