### ISSUE TITLE
Driver for Windows 7

### ISSUE THREAD

**Issue by sleveel** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#135]
Hello,

Whilst the board connects without issues to Windows 10 PCs, it looks lile it is not possible on earlier OS.

Does a driver exists for Windows 7?

Many thanks,
Stephane.

**Comment by LilyGO** [comment]
Hello, you can download through this understanding.
[download](http://www.wch.cn/downloads/CH343SER_EXE.html)

**Comment by sleveel** [comment]
[image: image.png]
