### ISSUE TITLE
Making/Answering calls & Sending/Receiving SMS TTGO TCAL TSIM7000G

### ISSUE THREAD

**Issue by bencypg** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#138]
Hi,

Is it possible to make or receive calls and Send/Receive SMS on LILYGO TTGO T-SIM7000G ESP32 with TinyGSM library?

Is there any other library that can do this along with getting GPRS data?

**Comment by alex-savin** [comment]
It is not supposed to to it! Only to support IoT LTE (LTE-M and NB-IoT)
