### ISSUE TITLE
SIM7000 vs A7670

### ISSUE THREAD

**Issue by JMvanE** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#139]
Dear all, 

Do I see it correctly that the main difference between the LilyGO T-SIM7000(G) and the T-SIM-A7670(E) boards is LTE CAT m1/NB-iot (SIM7000) vs 4G connectivity(A7670)?

Questions concerning these 2 boards:
- Are both boards completely Pin compatible and even AT compatible? 
- Are thee other differences between the boards?

Thanks for the input and help.

**Comment by LilyGO** [comment]
The A7670 series is the LTE Cat 1 module which supportswireless communication modes of LTE-TDD/LTE-FDD/GSM/GPRS/EDGE. It supports maximum 10Mbps downlinkrate and 5Mbps uplink rate.

AT instruction compatible 7600.A7670 does not support GNSS.Our team is rolling out the A7670-R2.The A7670-R2 has more GNSS and analog audio interfaces than the A7670, and supports receiving and making calls.

A higher correlation with 7000G is 7070G.The SIM7070 series is the LPWA module which supports wireless communication modes of Cat-M/Cat-NB/GPRS/EDGE.
