### ISSUE TITLE
Modem turns on & off periodically in short time intervals

### ISSUE THREAD

**Issue by jonrot1906** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#144]
Hey folks,
I currently can't get my LilyGo-T-SIM7070G module to work properly. When trying the NetworkTest sketch in the example folder the modem does connect over NB-Iot but will turn off completely after a few seconds (status and network led will turn off and won't respond to AT commands). This process repeats infinitely. I tried to do a factory reset, but this always fails on this device.

With Mongoose OS and the PPPos library I couldn't get the device to work permanently at all.

Device is connected per USB to my laptop, no battery inserted, no solar panel attached. Network Carrier is 1NCE, NB-Iot is possible.

Any help is appreciated!

**Comment by LilyGO** [comment]
+CGREG:0,5 indicates to register with roaming network.
It has to do with your SIM card. The serial port is connected to the network. Everything looks fine.

**Comment by jonrot1906** [comment]
Sorry that I left this topic uncommented for so long. My personal workaround was to do the following:
Turn on:
```pinMode(PWR_PIN, OUTPUT);
digitalWrite(PWR_PIN, LOW);
delay(1200);
digitalWrite(PWR_PIN, HIGH);
delay(300);
digitalWrite(PWR_PIN, LOW);
delay(10000);
```

Turn off:
```digitalWrite(PWR_PIN, HIGH);
delay(1500);
digitalWrite(PWR_PIN, LOW);
```

This does work on all my SIM7070G equipped devices (ESP32 + SIM7070G and also my [Waveshare SIM7070G Raspberry Pi Hat](https://www.waveshare.com/sim7070g-cat-m-nb-iot-gprs-hat.htm)). With "normal" turn on as provided in your examples, the modem will keep rebooting every 14 seconds or so.

**Comment by szundi** [comment]
Hello, just FYI: according to the docs, if you keep the PWRKEY pin DOWN for 12.6sec, it resets.

**Comment by rhr407** [comment]
I receive no response for HTTP Get request for the `http://httpbin.org/get` URL. Following is the output using the AT Command Tester from `https://m2msupport.net`

```

Checking registration status...

AT+CREG?

+CREG: 2,1,"912","3D73",0

OK
The device is registered in home network.

AT+CGREG?

+CGREG: 2,1,"912","3D73",0,"1"

OK
The device is registered in home network.

Device is registered.. 

Check the network APN...

AT+CGNAPN

+CGNAPN: 0,""

OK
Network did not send APN to the device.
Activate the network bearer...

AT+CNACT=0,1

OK

+APP PDP: 0,ACTIVE
Set up the HTTP URL...

AT+SHCONF="URL","httpbin.org"

OK
Set up the HTTP body length...

AT+SHCONF="BODYLEN",1024

OK
Set up the HTTP header length...

AT+SHCONF="HEADERLEN",350

OK
Initiating HTTP connection...

AT+SHCONN

OK
Get the HTTP connection state...

AT+SHSTATE?

+SHSTATE: 1

OK
HTTP connection is successful...

HTTP get request...

AT+SHREQ="http://httpbin.org/get",1

OK
No reponse received..

```

**Comment by Gabriel-Gardin** [comment]
Hello, I was having the same problem, SIM7070 board was reseting in short periods of time, when I chagned my code to turn on the board using: 
`pinMode(PWR_PIN, OUTPUT);
digitalWrite(PWR_PIN, HIGH);
delay(300);
digitalWrite(PWR_PIN, LOW);`

then it start working. 

Apparently SIM7000G and SIM7070G have different power on GPIO requirements.

**Comment by deeja** [comment]
Have been looking at this myself. 
As @Gabriel-Gardin  said, changing the PWR_PIN to LOW stops this.
The reason is that setting to HIGH sets the inverted value of PWR_KEY on the SIM7070 module to LOW. 
When held LOW for 12 seconds, the module resets. 
From the 7070 hardware design manual:
> After the PWRKEY continues to pull down more than 12S, the system will automatically reset. Therefore, long-term grounding is not recommended

This is different from the SIM7000 which has a reset pin

**Comment by Nadeem-Ullah** [comment]
Hey folks,!
I am using SIMCom SIM7070G module  ,for Cellular communication, connected to Raspberry Pi through Mini-PCIe USB connector. I created connection interface PPP0 using _mmcli_ and _nmcli_ commands through Network and Modem Manager.
When I ping google for testing, the GSM module hangs-up after ~50 minutes and can't capture the SIM-card while SIM index shows-up, ping do not work after that.
ERROR:(output of the "mmcli -m %modem-index -K" command running in my C programming for pinging at the instant of failure):

> "modem.generic.state : failed
> modem.generic.state-failed-reason : sim-missing
> 
> modem.generic.sim : /org/freedesktop/ModemManager1/SIM/0"

What may be the problem?
  

Your feedback is appreciated!

**Comment by Nadeem-Ullah** [comment]
> Upload.from.GitHub.for.iOS.MOV 
> Please see my short video which shows what I mean. This happens while running the "NetworkTest" sketch.
> 
> As I have obtained a few devices, I will try another one soon and report if the problems are occurring there as well.

Did you solved your problem?

**Comment by rhr407** [comment]
To the best of my knowledge SIM7070 and Sim7000 do not work with RPi on qmi
interface.

**Comment by rhr407** [comment]
No

**Comment by jonrot1906** [comment]
> Hey folks,! I am using SIMCom SIM7070G module ,for Cellular communication, connected to Raspberry Pi through Mini-PCIe USB connector. I created connection interface PPP0 using _mmcli_ and _nmcli_ commands through Network and Modem Manager. When I ping google for testing, the GSM module hangs-up after ~50 minutes and can't capture the SIM-card while SIM index shows-up, ping do not work after that. ERROR:(output of the "mmcli -m %modem-index -K" command running in my C programming for pinging at the instant of failure):
> 
> > "modem.generic.state : failed
> > modem.generic.state-failed-reason : sim-missing
> > modem.generic.sim : /org/freedesktop/ModemManager1/SIM/0"
> 
> What may be the problem?
> 
> Your feedback is appreciated!

QMI didn't work for me as well, I use PPP with all the SIM7000/SIM7070 devices connected to my RPis. For convenience I modified some Sixfab code and created a [repo](https://github.com/BUSSE-IS/rpi-sim70X0). Have a look if you want. Works perfectly fine for me.

**Comment by rhr407** [comment]
Thanks, I will have a look.

**Comment by Nadeem-Ullah** [comment]
I didn’t used @qmi interface, I have used Modem Manager and Network Manager and it created ppp0 interface, as _ifconfig_ shows…

**Comment by Nadeem-Ullah** [comment]
> I didn’t used @qmi interface, I have used Modem Manager and Network Manager and it created ppp0 interface, as _ifconfig_ shows…

Ohhh! sorry:

> In addition, install the libqmi-utils and udhcpc packages.
> 
> sudo apt install libqmi-utils udhcpc

I have used qmi indeed.


I will try the PPP0 new method.

But how _libqmi-utils_ produces _ppp0_ interface, as I have created it...?

**Comment by Nadeem-Ullah** [comment]
> > Hey folks,! I am using SIMCom SIM7070G module ,for Cellular communication, connected to Raspberry Pi through Mini-PCIe USB connector. I created connection interface PPP0 using _mmcli_ and _nmcli_ commands through Network and Modem Manager. When I ping google for testing, the GSM module hangs-up after ~50 minutes and can't capture the SIM-card while SIM index shows-up, ping do not work after that. ERROR:(output of the "mmcli -m %modem-index -K" command running in my C programming for pinging at the instant of failure):
> > > "modem.generic.state : failed
> > > modem.generic.state-failed-reason : sim-missing
> > > modem.generic.sim : /org/freedesktop/ModemManager1/SIM/0"
> > 
> > 
> > What may be the problem?
> > Your feedback is appreciated!
> 
> QMI didn't work for me as well, I use PPP with all the SIM7000/SIM7070 devices connected to my RPis. For convenience I modified some Sixfab code and created a [repo](https://github.com/BUSSE-IS/rpi-sim70X0). Have a look if you want. Works perfectly fine for me.

Hi: @jonrot1906 
In your repo you haven't provided the "README" file that explains how to install and use the library.
Help, please.

**Comment by jonrot1906** [comment]
> > > Hey folks,! I am using SIMCom SIM7070G module ,for Cellular communication, connected to Raspberry Pi through Mini-PCIe USB connector. I created connection interface PPP0 using _mmcli_ and _nmcli_ commands through Network and Modem Manager. When I ping google for testing, the GSM module hangs-up after ~50 minutes and can't capture the SIM-card while SIM index shows-up, ping do not work after that. ERROR:(output of the "mmcli -m %modem-index -K" command running in my C programming for pinging at the instant of failure):
> > > > "modem.generic.state : failed
> > > > modem.generic.state-failed-reason : sim-missing
> > > > modem.generic.sim : /org/freedesktop/ModemManager1/SIM/0"
> > > 
> > > 
> > > What may be the problem?
> > > Your feedback is appreciated!
> > 
> > 
> > QMI didn't work for me as well, I use PPP with all the SIM7000/SIM7070 devices connected to my RPis. For convenience I modified some Sixfab code and created a [repo](https://github.com/BUSSE-IS/rpi-sim70X0). Have a look if you want. Works perfectly fine for me.
> 
> Hi: @jonrot1906 In your repo you haven't provided the "README" file that explains how to install and use the library. Help, please.

Hi @Nadeem-Ullah,
I added some info to the repo, hope that helps. You should be fine simply running the "install.sh" script.

And well, ModemManager/mmcli uses qmi ports/protocol to my knowledge. For the SIM7600 module QMI is the way to go for me as it is faster, but for SIM7000/SIM7070 I found PPP to work far more reliable.

**Comment by Nadeem-Ullah** [comment]
I am not using SIM7070G HAT for RPi but my own development board with CM4 inserted in it.Then I inserted SIM7070G through Mini-PCIe.

Is there any specific PIN configuration to be changed in your scripts (According to my development board) or its all okay?

**Comment by Nadeem-Ullah** [comment]
> > > > Hey folks,! I am using SIMCom SIM7070G module ,for Cellular communication, connected to Raspberry Pi through Mini-PCIe USB connector. I created connection interface PPP0 using _mmcli_ and _nmcli_ commands through Network and Modem Manager. When I ping google for testing, the GSM module hangs-up after ~50 minutes and can't capture the SIM-card while SIM index shows-up, ping do not work after that. ERROR:(output of the "mmcli -m %modem-index -K" command running in my C programming for pinging at the instant of failure):
> > > > > "modem.generic.state : failed
> > > > > modem.generic.state-failed-reason : sim-missing
> > > > > modem.generic.sim : /org/freedesktop/ModemManager1/SIM/0"
> > > > 
> > > > 
> > > > What may be the problem?
> > > > Your feedback is appreciated!
> > > 
> > > 
> > > QMI didn't work for me as well, I use PPP with all the SIM7000/SIM7070 devices connected to my RPis. For convenience I modified some Sixfab code and created a [repo](https://github.com/BUSSE-IS/rpi-sim70X0). Have a look if you want. Works perfectly fine for me.
> > 
> > 
> > Hi: @jonrot1906 In your repo you haven't provided the "README" file that explains how to install and use the library. Help, please.
> 
> Hi @Nadeem-Ullah, I added some info to the repo, hope that helps. You should be fine simply running the "install.sh" script.
> 
> And well, ModemManager/mmcli uses qmi ports/protocol to my knowledge. For the SIM7600 module QMI is the way to go for me as it is faster, but for SIM7000/SIM7070 I found PPP to work far more reliable.

I am not using SIM7070G HAT for RPi but my own development board with CM4 inserted in it.Then I inserted SIM7070G through Mini-PCIe.

Is there any specific PIN configuration to be changed in your scripts (According to my development board) or its all okay?

**Comment by jonrot1906** [comment]
@Nadeem-Ullah Well, you need to specify then which board you are using. I used [this](https://www.waveshare.com/wiki/Compute_Module_4_PoE_4G_Board) Compute Module 4 PoE 4G Waveshare board with a SIM7600 module and got it to connect to the network by using a PPP connection over a ttyUSB port. This was quite similar to the "standard procedure" of connecting a Waveshare board like [this](https://www.waveshare.com/wiki/SIM7070G_Cat-M/NB-IoT/GPRS_HAT) to a RPi 3/4 via USB. In the end it's basically the same: the script will send some AT commands over a serial connection to the board. If it's over Mini-PCIe or USB wouldn't matter I guess.

**Comment by Nadeem-Ullah** [comment]
I am using CM4 like [this](https://www.raspberrypi.com/products/compute-module-4/) in my own development board, having same PINS as Raspberry Pi 4 B. And connected SIM7070G board through Mini-PCIe with this CM4 using my development board extension.
It is detecting ttyUSB ports as well. And Serial Port (ttyAMA0) also works fine for sending AT commands. May be its a M.2 connection you mentioned above.
But for module power control, I am using GPIO23 of the Raspberry Pi and giving a Power Supply at Vbat PIN to the module. So, should I use PIN-23 instead of PIN-6 to be set to high for board to turn on?

**Comment by jonrot1906** [comment]
@Nadeem-Ullah As I really don't know how your development board extension is wired up, it's hard to tell. You could either share some more information or just try it out. :-)

**Comment by Nadeem-Ullah** [comment]
> @Nadeem-Ullah As I really don't know how your development board extension is wired up, it's hard to tell. You could either share some more information or just try it out. :-)

I am using SIM7070G in PPP mode and the '5 USB serial Modem port Interface' is 'ttyUSB5' in this mode. as shown in the picture below:
![Screenshot from 2024-08-01 15-19-19](https://github.com/user-attachments/assets/12c6318b-bd98-4c61-8a98-2a22033deb51)

In which mode should I use the module?

If 'ttyUSB5' is correct for me, should I edit the file [reconnect_sim7000.sh](https://github.com/BUSSE-IS/rpi-sim70X0/blob/main/reconnect_sim7000.sh), replacing 'ttyuSB3 with 'ttyUSB5', according to my situation.

Another point is I have the 'AT+CPOWD=1' option in my module datasheet, can I use it directly instead of GPIO PIN for power off and on, as shown in file [reconnect_sim7070.sh](https://github.com/BUSSE-IS/rpi-sim70X0/blob/main/reconnect_sim7070.sh) ?

Another point is that you have used the 'wwan0' interface in your script in files [reconnect_sim7070.sh] and [reconnect_sim7000.sh], in which both have no 'wwan0' interface USB port except [SIM7500_SIM7600], as shown below, from the datasheets of these modules:

![Screenshot from 2024-08-01 15-19-19](https://github.com/user-attachments/assets/a9001046-ccf7-4e1b-9374-948efcff9e08)
![Screenshot from 2024-08-01 16-17-21](https://github.com/user-attachments/assets/2ab13ebd-deb7-4043-a63a-6063588b95f7)
![Screenshot from 2024-08-01 16-18-44](https://github.com/user-attachments/assets/3c1d1ae6-29bb-47ab-9971-76500a02c33f)

Should I replace 'wwan0' with 'ppp0' or its ok?

In file [reconnect.sh](https://github.com/BUSSE-IS/rpi-sim70X0/blob/main/reconnect.sh) you have used 'GPIO-7' and 'sudo /etc/init.d/rinetd restart' also, whats the purpose of these both and how I should replace these?

In the file [provider](https://github.com/BUSSE-IS/rpi-sim70X0/blob/main/provider) you have used '/dev/ttyUSB2 115200' which is understandable (AT command port) and _-T iot.1nce.net_ is also known as APN and I will replace it according to my ISP's APN.

Another question is that in the installation you have said: _Simply cd into the repo and run_, so, which _repo_ we should cd to or you talking about _**/etc**_ file directory?

help, please
