### ISSUE TITLE
Battery percentage

### ISSUE THREAD

**Issue by realbeeit** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#161]
Hi, 
is it possible to read battery percentage? I can read battery and solar voltage but I didn't found anything about percentage.

**Comment by LilyGO** [comment]
Hello，The battery is about 4.2V at full charge, and you can get the percentage by comparing the voltage you get to 4.2

**Comment by LilyGO** [comment]
Around 2.7V, you can check according to the actual situation
