### ISSUE TITLE
Links on Github does not work

### ISSUE THREAD

**Issue by Gouzi001** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#169]
https://github.com/Xinyuan-LilyGO/LilyGO-T-SIM7000G/tree/master/frimware

Link shall point to https://www.espressif.com/en/support/download/other-tools

+New Flasher 3.9.2 interface looks bit different -> replace screenshot for dummies :)

**Comment by LilyGO** [comment]
Thanks for the reminder. Fixed and updated
