### ISSUE TITLE
Aliexpress.  Shipping to Germany is no longer possible!

### ISSUE THREAD

**Issue by vladco78** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#184]
Hi Lilygo,
Aliexpress.  Shipping to Germany is no longer possible!
What is known here?  Where else can I buy this board?

**Comment by LilyGO** [comment]
Hello. We're working on it. We'll be done soon

**Comment by LilyGO** [comment]
You can also buy them [here ](https://www.tindie.com/products/lilygo/lilygo-ttgo-t-sim7000g/)
