### ISSUE TITLE
GSM CALLING FAILED. ATD RETURNS ERROR

### ISSUE THREAD

**Issue by jishnupsy** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#192]
Hii,
i recently bought this module and i have been playing with it. but i couldn't place a normal **GSM CALL** using the atdxxxxxxxx; command.
i am using the **NETWORKTEST SAMPLE** code. after the network is connected  other at commands are working , AT returns ok ,but the 
ATD command returns error. i am using the antenna comes with the module.
any possible reasons for this , or please suggest any methods to resolve this
**thanks in advance**.

**Comment by LilyGO** [comment]
7000G does not support voice calls

**Comment by jishnupsy** [comment]
thanks
