### ISSUE TITLE
SIM7000G LilyGo PWR button is it not connected?

### ISSUE THREAD

**Issue by muhiddinov** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#198]
Hi there!
I don't know what the PWR button does here, and I can't find any information on the schematic where it's connected.
[Here is the schematic layout](https://raw.githubusercontent.com/Xinyuan-LilyGO/LilyGO-T-SIM7000G/master/schematic/SIM7000G_20191227.pdf)
In this schematic drawing I only see 1 button and it is connected to EN or RESET pin of ESP32.

**Comment by LilyGO** [comment]
Hello, PWR is connected to SIM7000 module
