### ISSUE TITLE
Unable to get SDCard working. Bad Board?

### ISSUE THREAD

**Issue by tweathers-sec** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#206]
Unable able to get the SDCard working. Bad board? 

Using many variants of the sample code provided, I continue to get the following error. Yes, the SDCard is formatted to FAT.

`
[  1821][E][sd_diskio.cpp:802] sdcard_mount(): f_mount failed: (13) There is no valid FAT volume
SDCard MOUNT FAIL
`

Relevant Code Used - Snipped for brevity.

```
#include <SD.h>
#include <SPI.h>
#include <LittleFS.h>

#define SD_MISO 2
#define SD_MOSI 15
#define SD_SCLK 14
#define SD_CS 13

void setup()
{
    SPI.begin(SD_SCLK, SD_MISO, SD_MOSI, SD_CS);
    if (!SD.begin(SD_CS)) {
        Serial.println("SDCard MOUNT FAIL");
    } else {
        uint32_t cardSize = SD.cardSize() / (1024 * 1024);
        String str = "SDCard Size: " + String(cardSize) + "MB";
        Serial.println(str);
    }
}
```

**Comment by Tig3rch3n** [comment]
Have you tried a different brand of SD Cards?
I had some Trouble with 'NoName' SDCards

They work under Windows/Linux/Android no Problem.
But for some reason they don't support "SPI Mode" so they are useless for any Arduino Projects.
Seytonic did a Video about the Topic a few days ago https://youtu.be/wNfpRwQgDG4

**Comment by tweathers-sec** [comment]
Thanks for the recommendation, but I don't use off label cards for that specific reason. I have tested a number of different SanDisk and Kingston cards that work fine with my other ESP32's. For whatever, this board just doesn't like them.

**Comment by Tig3rch3n** [comment]
Could you post the full Code?
I can test in Tonight/Tomorrow :)

**Comment by tweathers-sec** [comment]
Sure thing... So far, I have just been using the Examples provided in this repo. 

https://github.com/Xinyuan-LilyGO/LilyGO-T-SIM7000G/blob/master/examples/Arduino_NetworkTest/Arduino_NetworkTest.ino

**Comment by lewisxhe** [comment]
My test is normal.
1. Please try to add pinMode (SD_MISO, INPUT_PULLUP) before SPI.begin; Test whether it is normal
2. Make sure the SD card is FAT format and accessible on the computer
If it still doesn't work, I suspect that there is a problem with the SD card seat welding

![image](https://user-images.githubusercontent.com/22990954/210295886-1f340edf-b174-44ee-9d43-a46d39d51a9e.png)

**Comment by Tig3rch3n** [comment]
> Sure thing... So far, I have just been using the examples provided in this repo.
> 
> https://github.com/Xinyuan-LilyGO/LilyGO-T-SIM7000G/blob/master/examples/Arduino_NetworkTest/Arduino_NetworkTest.ino

Just tested it with my Version 20200415 Board, I had to Comment out the Modem Init (no IoT Sim yet)
But everything works out of the Box with a ext3 Formating 
I get 

> ========INIT========
>========SDCard Detect.======
>SDCard Size: 30436MB
>===========================

**Comment by tweathers-sec** [comment]
Thanks all for the input. It was certainly a bad connection with the PCB. I ended up doing an exchange for a new board and my code is working without issue. Closing this out.
