### ISSUE TITLE
Unable to mount SD card

### ISSUE THREAD

**Issue by MatthewFehl365** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#216]
Hello all,

I'm trying to run some example scripts using the SD card slot but I am unable to mount the card. Has anyone tried this? Does it need to be formatted to  certain filesystem type? 

Thank you for any help you guys can provide!

Regards,

Matthew Fehl

**Comment by iliDaedalus** [comment]
A bit old answer but as I read here https://esp32.com/viewtopic.php?t=18437:
`SD card APIs support the FAT filesystem.
SD cards larger than 32GB as per SDXC standard are formated using the exFAT file system and won't work with the ESP-IDF.`

**Comment by MatthewFehl365** [comment]
Fixed the issue
