### ISSUE TITLE
Please publish schematics for latest LilyGO-T-SIM7000G board revision

### ISSUE THREAD

**Issue by kapitan-u** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#22]
Please publish schematics for latest LilyGO-T-SIM7000G board revision. Thank you!

**Comment by lewisxhe** [comment]
Sorry, it will be updated on Monday

**Comment by lewisxhe** [comment]
The schematic and related descriptions have been updated

**Comment by kapitan-u** [comment]
Thank you!
