### ISSUE TITLE
Mismatched IMEI number and unable to connect to network on SIM7000G

### ISSUE THREAD

**Issue by cfficaurzua** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#236]
Hello,

I have encountered a problem with my LILYGO SIM7000G module where the IMEI number reported by the AT+GSN command does not match the IMEI number printed on the device's sticker and in the QR code.

Expected Behavior

When I issue the command AT+GSN, the IMEI number returned should match the one printed on the sticker and in the QR code, which is 869951035781347.

Actual Behavior

The AT+GSN command returns the IMEI number 860371050882459, which is different from the one on the sticker and QR code.

Here's the output of AT+SIMCOMATI:

```
Revision:1529B08SIM7000G
CSUB:V01
APRev:1529B08SIM7000,V01
QCN:MDM9206_TX3.0.SIM7000G_P1.03_20200903
IMEI:860371050882459
```
Additionally, I am unable to connect to the network, which may be related to this issue.

Steps to Reproduce

Issue the AT+GSN command to the module.
Compare the returned IMEI number with the one printed on the sticker and in the QR code.
Potential Solutions

I'm not sure how to proceed to resolve this issue. I have considered checking for a firmware update and contacting the module's manufacturer. I welcome any suggestions you may have.

Thank you for your assistance!

**Comment by jjharlow** [comment]
Check this out. https://github.com/Xinyuan-LilyGO/LilyGO-T-SIM7000G/issues/214#issuecomment-1421806928
