### ISSUE TITLE
Board not listed in "Other Devices" within Device Manager

### ISSUE THREAD

**Issue by vm-57** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#285]
I recently purchased a T-SIM7000G device, which I have been attempting to use with my Windows 11 laptop. However, when I plug in the device, it does not appear in Windows Device Manager. While the USB connection between my computer and the board is listed under the Ports section, nothing appears under "Other Devices." I have tried connecting the board to several different Windows computers, but have encountered the same issue each time. I am writing to ask what steps I should take to ensure the board registers as a device. Any suggestions would be appreciated.

**Comment by lewisxhe** [comment]
No device is displayed after plugging into the PC? Device management does not even change? If so, provide a test video and contact the dealer for after-sales service

**Comment by lewisxhe** [comment]
If CH9102 is detected, it is normal. This is a USB2TTL bridge. The other device you mentioned should refer to the USB port of SIM7000, right? Only the USB port of SIM7000G on the board is connected. It is impossible to directly connect the port of SIM7000G via USB-C. See here
https://github.com/Xinyuan-LilyGO/LilyGO-T-SIM7000G/blob/master/docs/How%20to%20update%20firmware.md

**Comment by lewisxhe** [comment]
It depends on whether you want to use the network. The USB connection has nothing to do with the SIM card.

**Comment by lewisxhe** [comment]
If you only want to program ESP32, just plug in USB-C, open the sketch, select the CH9102 port and upload.
If you want to access the USB port of SIM7000G, you must connect additional wires to the position of the picture
