### ISSUE TITLE
Sim7000g LTE Cat-M1 support and cellular + gps simultaneous support

### ISSUE THREAD

**Issue by swebt** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#293]
Hi, hope all is well

We are working on development using the sim7000g we purchased. 

some questions:
On the GitHub main page it mentions “ SIM7000/SIM707G does not support 4G network. Please ensure that the USIM card you use supports 2G(GSM)/NB-IOT access,SIM7070 positioning and cellular cannot be used simultaneously. Please disconnect the network when positioning, and turn off GPS when connecting to the network”

1. Does this mean that the Sim7000g does not work with LTE CAT-M1 state? The Sim7000 chip I think should support this but I’m not sure if this module supports that state?
2. It says the Sim7070 cannot use positioning and cellular simultaneously. Does this also apply to the Sim7000g?

thank you for the clarification.

**Comment by lewisxhe** [comment]
SIM7000G only supports simultaneous GPS and data
SIM7070G does not support

**Comment by swebt** [comment]
Great thanks!

sim7000g works with LTE Cat-M1?

**Comment by lewisxhe** [comment]
![image](https://github.com/user-attachments/assets/b925726e-f64b-45f1-9f2e-b17b39a87f5d)
Yes

**Comment by swebt** [comment]
Great thank you!
