### ISSUE TITLE
Instructions to setup the Arduino IDE?

### ISSUE THREAD

**Issue by Humancell** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#33]
Where can I find the instructions for setting up the Arduino IDE to program this device?

**Comment by Humancell** [comment]
Here is an update:

Following the instructions here:  https://sites.google.com/site/jmaathuis/arduino/lilygo-ttgo-t-display-esp32

I did add the ESP32 Boards file from here: https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md

Now I do see a long list of ESP32 compatible boards ... but not this one!

Which one do I select?  Do I follow the instructions in the link above and select "ESP32 Dev Module" and the rest of this parameters?

**Comment by Mr-HaleYa** [comment]
select esp32 dev board at the top... then select the port it's connected to and that's all, nothing fancy. 

![47](https://user-images.githubusercontent.com/42821995/85628874-15e06600-b62e-11ea-9e65-2ee651eda397.PNG)

**Comment by Mr-HaleYa** [comment]
@Humancell  @lewisxhe 
This can be closed as it's not an issue but rather a lack of understanding how to use Arduino IDE. Also the solution was given
