### ISSUE TITLE
T-SIM7000 evaluation and improvements

### ISSUE THREAD

**Issue by nikil511** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#4]
I have been playing with T-SIM7000 since December last year. We got some beta hardware, slightly different to the one on sale today.

I can confirm that everything works as it should, including NBIoT with PSM sleep (~1mA)
So overall very nice module, low power, connects to network even with battery at 2.8v.

Issues found so far:
1) was missing 100k resistor from BAT voltage divider (this could be because of beta hardware)

2) SOLAR input +/- marking is under the plug, thus not visible. Also its better to reverse the plug to be seeed-studio solar panel polarity compatible (in my point of view). Keep in mind that a solar bellow 1W will not charge the battery. (1W@5V = 80x100mm). Would be nice to start charging from 0.5W for use-cases that TSIM is not uploading very frequently or when there are clouds.

3) battery drain auto-boot seems ok but not perfect. It only pulls 35μΑ at 2.7V and everything is turned off (ESP32 and 3v3 line off). However, when solar power is provided and the battery has recovered, **sometimes** ESP32 boots in to "download mode" so it is working, but still needs a reset button :-( Some kind of reset supervisor or battery cut off protector should be used to make sure that ESP32 boots properly when power is recovered slowly via solar.

4) SIM socket adapter is easy to brake, replace with a better one.
We have x10 T-CALLs on the field (same sim adapter) and some of them broke during attempts to replace sim cards. I think the sockets that you slide the sim-card inside are safer more robust. (also they could be used a JTAG debugger )

**Comment by lewisxhe** [comment]
The situation you said, we will test it, thank you for your feedback

**Comment by nikil511** [comment]
@lewisxhe I performed more tests. The empty-battery-solar-charge boot problem happens only with one of the modules I have. The other one always boots fine. So maybe some component value is on the borderline.

**Comment by lewisxhe** [comment]
I do n’t have T-SIM right now, I ca n’t do more tests. When T-SIM arrives, I will do more tests on power consumption. After the test is complete, I will summarize the summary of the next revision.

**Comment by Mr-HaleYa** [comment]
1. was fixed
2. the markings were moved (the plug was not reversed 😞 but probably best bc my circuits would explode now)
3. this seems to be fixed with the new board (boot correctly when I charge from dead with solar)
4. same socket, unfortunately. they should have a more robust one 

If you feel your issue has been resolved, please close 🙂

**Comment by lewisxhe** [comment]
The new board has been improved design, this issue will be closed

**Comment by javipelopi** [comment]
Hi!

@nikil511 why do you say " Keep in mind that a solar bellow 1W will not charge the battery. (1W@5V = 80x100mm)." ?

Is it a limitation of cn3065 chip? Has it been solved in the final version?

Thanks in advance!
