### ISSUE TITLE
Questions about board (20200415)

### ISSUE THREAD

**Issue by Mr-HaleYa** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#40]
So I hooked a battery to the vbat pin and gnd backwards and this component exploded....

What is it? Why did it? isn't there supposed to be backwards battery protection or is that only if you use the socket on the back?

![IMG_20200710_031843.jpg](https://user-images.githubusercontent.com/42821995/87138865-4a723580-c25c-11ea-8b35-48197dbf1a80.jpg)

**Comment by lewisxhe** [comment]
Sorry, I will report the situation to the hardware engineer, and I will ask them what to do.

**Comment by slavino** [comment]
> Sorry, I will report the situation to the hardware engineer, and I will ask them what to do.

maybe bigger "BAT +" and "BAT -" signs on the board in next HW version :D

**Comment by Mr-HaleYa** [comment]
It was an external battery pack, but yes they could put bigger symbols on the back

**Comment by lewisxhe** [comment]
Did you use the rear 18650 battery holder to access the battery before? Is it normal ?

**Comment by Mr-HaleYa** [comment]
What? Is it normal for things to explode? No it is not normal... yes I use the rear battery pack and it worked just fine but then I desoldered the rear pack and soldered a larger one to vbat and gnd and accidentally put one battery in backwards and the part exploded. I did the exact same thing to five other boards and as long as you don't put the battery in backwards they don't explode.

**Comment by lewisxhe** [comment]
No, you misunderstood, I mean, have you used the battery holder provided on the back of the board for charging before?  Is it normal?  Or is it your first time using the charging function?

**Comment by Mr-HaleYa** [comment]
I said yes I used it, then I removed it.

**Comment by Mr-HaleYa** [comment]
@lewisxhe 
any other questions? did your engineer reply?

What part is it and where is it on the schematic and I will replace it.

**Comment by lewisxhe** [comment]
![image](https://user-images.githubusercontent.com/22990954/87652177-79216c00-c786-11ea-97fd-b6fed9c4318e.png)

This is a boost IC, you can replace it if you can

**Comment by nissimzur** [comment]
This chip boost Vbat 3.6 to 4.2 needed by GSM.
If you remove U11, you can hook to C32 the plus side to external 4.2 V
if you use USB 5V. you can put a diode in series
![add](https://user-images.githubusercontent.com/3673671/87752873-0c4fb580-c80a-11ea-994b-c9bd86d82845.png)
 with 5V and get easy 4.2 V.

**Comment by Mr-HaleYa** [comment]
@nissimzur 
are you the engineer/developer?

**Comment by nissimzur** [comment]
I am. 
look for Dr. Nissim Zur at youtube

**Comment by Mr-HaleYa** [comment]
I was if you are the person who built the TTGO SIM7000G?

**Comment by lewisxhe** [comment]
This is a stupid approach, and the Modem may not be turned on when using battery power. He is not an engineer of LilyGo.

**Comment by lewisxhe** [comment]
The method of connecting the diode in series does not consider the use of battery power supply. When the battery is used, the Modem may not be opened smoothly

**Comment by lewisxhe** [comment]
The engineer just told me to use the negative battery on the back of the board instead of GND, which has battery over-discharge, overload, and short-circuit protection.

**Comment by Mr-HaleYa** [comment]
That's not an option, its mounted on a PCB
![IMG_20200715_063354](https://user-images.githubusercontent.com/42821995/87898600-d4b05b80-ca0b-11ea-82d5-968c75b3b9f8.jpg)

**Comment by Mr-HaleYa** [comment]
@lewisxhe 
Ok, I rebuilt my PCB to have spring contacts to connect to the Battery pins on the back of the TTGO when it is mounted on a PCB. This should add the following benefits 
- Backward battery protection
- overcharge Protection
- Over-Discharge protection
- overcurrent protection
- on/off switch

I think I will still add an STM1061N27WX6F To monitor the battery and force the MCU off (RST LOW) until the voltage is greater than 2.7v so it does not give the bootloader problem
