### ISSUE TITLE
Power question

### ISSUE THREAD

**Issue by Mr-HaleYa** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#41]
If I hook a battery to Vbat and GND so that is being powered, Do I need to remove the battery before plugging into USB? I have plugged into USB with battery in the socket on the back but never with an external battery. I don't want to fry another board...

**Comment by lewisxhe** [comment]
Yes, I just did the test
![V OXSIFVD`VQU)O0)MFSAJS](https://user-images.githubusercontent.com/22990954/87519166-d00a4100-c6b3-11ea-9c24-a997505939f4.jpg)

**Comment by Mr-HaleYa** [comment]
So I can have battery connected as you do and plug-in USB?

**Comment by lewisxhe** [comment]
![IMG_20200716_155245](https://user-images.githubusercontent.com/22990954/87642886-b680fc00-c77c-11ea-90d7-b59ce98d80ca.jpg)
Yes, I tried again, no problem
