### ISSUE TITLE
Sim7000G and LoRa

### ISSUE THREAD

**Issue by rodri16** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#51]
Hi, do you have any example on how to connect and an example of Sim7000G and Lora Board? I would like to have a system with LoRa and NB-IoT connection according to radio coverage.

Here you say that it is possible to connect LoRa shield
[http://www.lilygo.cn/prod_view.aspx?TypeId=50033&Id=1246&FId=t3:50033:3](url)

**Comment by Mr-HaleYa** [comment]
That link goes nowhere...
Are you using an official LoRa board that is so along with there or is a 3rd party board if so give details, and images/links?

**Comment by slavino** [comment]
https://www.aliexpress.com/item/4000542688096.html

![image](https://user-images.githubusercontent.com/1584034/90215786-1363e680-ddfd-11ea-8335-47081168ee2e.png)

**Comment by 0lav** [comment]
I am going to be using one of these soon with the SIM7000G. I will share my results when its done. 

https://images-na.ssl-images-amazon.com/images/I/41KYtRSkaZL._AC_.jpg

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGO-T-SIM7000G/tree/master/examples/Arduino_Cayenne 
It is an example of applying LORA to TTN

**Comment by Mr-HaleYa** [comment]
@rodri16 @lewisxhe 
The solution was given and now they even sell a product for LORA so this should be closed
