### ISSUE TITLE
Ring indicator pin not connected

### ISSUE THREAD

**Issue by bindi** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#56]
Hello,
Will there be a new revision of the 7000 with the RI (Ring indicator, pin 4) pin available? This is a must-have for low power applications. I was disappointed to see it not connected on the 800 version, and yet again disappointed to see it left unused in this board as well.

**Comment by lewisxhe** [comment]
SIM7000 does not have the call function. You may buy the earlier version of IP5306 for SIM800. Later AXP192 power supply will have RI indication. After a while, IP5306 will be upgraded and RI indication will be connected to ESP32.

**Comment by bindi** [comment]
https://simcom.ee/documents/SIM7000E/SIM7000%20Hardware%20Design_V1.05.pdf
3.3.2 RI and DTR Behavior
Am I misunderstanding the datasheet or why does the sim7000 have the RI pin at all then? By call function do you mean it can not receive or send phone calls? The Ring Indicator can be used for incoming SMS.

**Comment by robbiet480** [comment]
@lewisxhe So did the RI pin get connected in the newer version of this board?

**Comment by lewisxhe** [comment]
@robbiet480 LilyGo products are no longer maintained by me, please contact LilyGo staff

**Comment by robbiet480** [comment]
Thanks for letting me know @lewisxhe!

@LilyGO Can you comment on if the RI pin is connected or not?

**Comment by LilyGO** [comment]
> Thanks for letting me know @lewisxhe!
> 
> @LilyGO Can you comment on if the RI pin is connected or not?



> Thanks for letting me know @lewisxhe!
> 
> @LilyGO Can you comment on if the RI pin is connected or not?

The pcie RI is connected to the main control.T-7000g We will connect the RI pin to the master in the new version
