### ISSUE TITLE
Timed out waiting for packet header

### ISSUE THREAD

**Issue by ro85ac** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#59]
I have the new board and I am getting this annoying issue when I try to upload. I google it and all the answers say to press the boot button, but I see on the board PWR and RST buttons. I pressed each one separately and also both of them in the same time, but nothing helped.

```
esptool.py v2.6
Serial port COM5
Connecting........_____....._____....._____....._____....._____....._____.....____An error occurred while uploading the sketch

A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header
```
 
![error](https://user-images.githubusercontent.com/11976725/93224743-1fcfbc00-f77a-11ea-8fec-88d935b3d74b.png)
![error_board](https://user-images.githubusercontent.com/11976725/93224746-20685280-f77a-11ea-93a3-094daceb9070.jpg)

**Comment by cuplesoft** [comment]
It looks like wrong port number.

wt., 15 wrz 2020, 16:40 użytkownik ro85ac <notifications@github.com>
napisał:

**Comment by ro85ac** [comment]
The board has a problem with the TypeC connector. It's moving inside it.
