### ISSUE TITLE
Fail to Attach service

### ISSUE THREAD

**Issue by ro85ac** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#6]
Hi Team,

First of all I am new in LilyGO-T-SIM7000G / Arduino world.

Unfortunately I am unable to use the board. I am getting the following error: "Fail to Attach service".
I would like to know if this a network operator error or I am doing something wrong?

I am charging the board at USB. The green and blue leds are always opened while the red led is blinking.

Thanks in advance!
Adrian
![error](https://user-images.githubusercontent.com/11976725/74187130-a0629300-4c54-11ea-8c4a-fed32a4a4531.png)

**Comment by lewisxhe** [comment]
Not every time you connect to the server, you can try to reset, or you can use TinyGSM, that is much better

**Comment by Mr-HaleYa** [comment]
@ro85ac close if you have fixed the problem
