### ISSUE TITLE
Voltage dividers for solar & battery

### ISSUE THREAD

**Issue by ROSW6341** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#60]
What is the tolerance for the voltage divider resistors R62, R63, R64 & R65?  After compensation for the ADC non-linearity the voltages are about 5% low.  I installed and external divider using 1% resistors between 3.3v & ground.  That voltage is read accurately (less than 1% off).

**Comment by lewisxhe** [comment]
After I asked, I learned that 5% was used. So the accuracy may be a little bit worse

**Comment by ROSW6341** [comment]
I 'trick' to use 5% resistors is to use a 2-pack (both resistors on the same substrate).  They might be off by 5% but will be in the same direction still maintaining a constant divide by 2.  A 4-pack could be used for the two dividers.  Unfortunately either would require a board spin.
