### ISSUE TITLE
Solar panel data

### ISSUE THREAD

**Issue by AR-poli** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#66]
Hi everyone,
I intend to buy the latest version of the T-CALL 7000G but I have some doubts about the type of solar panel to use to charge the battery. From previous discussions I have seen that, for the old version, 6V and 1A were recommended.
Now that it is equipped with IC solar chargher what has changed?

**Comment by Mr-HaleYa** [comment]
it is now a true solar charge chip and if you read the readme page you would see Notes For New Users, 5 says "Recommended solar panels are 4.4v to 6v **DO NOT EXCEED OR BOARD MAY BE DAMAGED**"
6v 1 amp will be fine. 

what changed with this new chip is also listed on the front readme
Added reverse battery protection
Added battery overcharge protection
Added battery over-discharge protection
