### ISSUE TITLE
Battery lifetime with solar panel and 15 min deep sleep 

### ISSUE THREAD

**Issue by jupiter8888** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#68]
Hi guys, nor really an issue but i'm building a sensor network and i don't actually have this fancy lab stuff to calculate the power consumed and the solar panel needed for my application.

Basically it will be 2 sensors, a bme280 to read atmospheric pressure and another pressure sensor MS5803-01BA (1.4A inrush current) to read underwater pressure.

The setup will be deployed this winter in canada (not too much sun), it will sleep for 15 min, wake up send data in json and go back to deep sleep.
So if anybody has an idea of the size of solar panel/number of batteries needed for this i would love to hear your recommendations and experiences.

Thanks.

**Comment by lewisxhe** [comment]
This has not been tested, this question will be closed
