### ISSUE TITLE
Failed Register to Network in Board 20200415 Version, but Successfully in 20191227 Version 

### ISSUE THREAD

**Issue by nazmibojan** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#70]
Hi,

I'm Nazmi and have been purchased two different version of LilyGO-T-SIM7000G board. In 20191227 version, my SIM card can easily registered to network after initialize. It was indicated by NETLIGHT status that was blinking every 3 seconds. But, in 20200415 version, my SIM Card could not register to network. NETLIGHT status always blinkiing every 800ms. If I run AllModemTest example I always got this:

![image](https://user-images.githubusercontent.com/17125575/97082630-487a8980-1635-11eb-8f1e-64f28e6791ed.png)

I have set networkMode to 13, which is GSM only. I also changed APN data to my operator's APN. My SIM card operator use 900MHz band for their 2G network. Please give any insight for solving my problem. Thank you.

Regards,
Nazmi

**Comment by jupiter8888** [comment]
One thing you can try is  writng the apn manually with the AT commant sketch. the command is: AT+CGDCONT=1,"IP","YOURAPN"
do that with each PDP context, i noticed there is context 13 active also, so it will be:  AT+CGDCONT=13,"IP","YOURAPN"
after check with AT+CGDCONT?

**Comment by lewisxhe** [comment]
You can check whether the two boards use the same options
AT+CNMP=? Return to current mode
AT+CNMP=2 set to automatic mode

**Comment by nazmibojan** [comment]
Hi,

Thanks All for your sugestion. But the problem is regulation in my country. Some new regulations have been launched in September about IMEI validation. I bought LilyGo from China without register its IMEI to related minister information system. So, it made my LilyGo couldn't register to LTE network.

Regards,
Nazmi
