### ISSUE TITLE
IO5 Reset Sim7000?

### ISSUE THREAD

**Issue by FreVanBE** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#71]
Dear, 
Do manipulations on IO5 trigger a reset of the SIM7000? 
According to my interpretations of the schematic it does, but how can the pin then be used as CS for the SPI-bus or other things, without resetting the radio?

Thanks.

**Comment by alepiva** [comment]
Schematic R40 is NC that means it is not mounted. So the circuit NRESET is not connected with IO5

**Comment by FreVanBE** [comment]
Thanks for the clarification.
