### ISSUE TITLE
Power question

### ISSUE THREAD

**Issue by EmanueleFeola** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#72]
Hi, electronic is not my field of competence, so I have this doubt:
in order to power correctly the esp32 and the sim7000 is it sufficient to plug in a 18650 battery?
When I'm running tests, while I have the 18650 battery inserted into the socket and the type-c of the board connected to a computer USB port, can I have power issues which cause the esp32 board with sim 7000 module to not work properly?

**Comment by lewisxhe** [comment]
The battery and USB can be connected at the same time, and it will not fail to work!

**Comment by EmanueleFeola** [comment]
Thank you, have a good day!
