### ISSUE TITLE
LilyGO-T-SIM7000G/examples/Arduino_TinyGSM is it really working?

### ISSUE THREAD

**Issue by Paryavi** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#76]
Hi, I bought two of 7000G boards, but the TinyGSM library does not support 7000G! **so is your Arduino code really work?**
I get this error; **#error "Please define GSM modem model"**

Details that TinyGSM library does not support 7000G;
`https://github.com/vshymanskyy/TinyGSM/blob/master/src/TinyGsmClient.h`
// typedef TinyGsmSim7000::GsmClientSecureSim7000 TinyGsmClientSecure; TODO!

Thanks

**Comment by procopio** [comment]
I used this example bellow few days ago, it also uses TinyGSM
https://github.com/Xinyuan-LilyGO/LilyGO-T-SIM7000G/blob/master/examples/Arduino_NetworkTest/Arduino_NetworkTest.ino

**Comment by lewisxhe** [comment]
Support, please refer to our example instead of running the TinyGSM built-in example directly.
