### ISSUE TITLE
Distinguish power source

### ISSUE THREAD

**Issue by Fullmono** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#77]
Hi, 

I would like to know if there is a way for the ESP32 to distinguish the power source between the battery and the usb-c?

(a solution could be to put a resistor between VIn and a gpio input but I'd like to avoid this one)

Thank you,

**Comment by procopio** [comment]
Yes, when it's connected to USB ADC(35) is zero.
If it's in battery it has a value.
