### ISSUE TITLE
capacitor parallel to R62 and R64?

### ISSUE THREAD

**Issue by alexseuf** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#78]
Hello everyone,
I have sporadically slighly wrong measurement values on ADC measurement of V_bat and Solar_in (appox. +/-5% from median value).
To reduce this, I would try to solder a SMD-100nF? Capacitor on top of R62 and R64.
Could you please tell me where I could find this resistors on the PCB?
Thank you

**Comment by Mr-HaleYa** [comment]
![image](https://user-images.githubusercontent.com/42821995/108798270-ab7c1e80-754a-11eb-8626-e7d818512163.png)
 
If this solved the issue please mark it as closed - Hale

**Comment by lewisxhe** [comment]
These two positions as shown in the figure 
![B6~AZR1IYYS14S~9`V UXEX](https://user-images.githubusercontent.com/22990954/109450021-e15a5f00-7a84-11eb-89a8-f07cfbc3818d.png)

**Comment by alexseuf** [comment]
Thank you lewis he,
please confirm, that the red marked resistores in my picture are R62 and R64?
The yellow marked resistors are wrong =>100R and not 100k (picture from  Mr-HaleYa ).
Thank you
![grafik](https://user-images.githubusercontent.com/48165001/109462654-202bed00-7a64-11eb-9fdc-902b65a5669a.png)

**Comment by lewisxhe** [comment]
yes !

**Comment by Mr-HaleYa** [comment]
@alexseuf sorry I got the wrong ones I dis say it was a guess but glad you got the right ones
