### ISSUE TITLE
Different modem (without TCP/IP, LTE Cat M1, NB-IoT)

### ISSUE THREAD

**Issue by Francois-37** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#79]
I ordered 2 boards and I received 2 differents cards.
On the picture we can see than we have IC on the modem without TCP/IP, LTE Cat M1, NB-IoT.
And the code exemple didn't work. You can try with the command AT+CMNB, if you force LTE only (38), when you read with +CMNB? you will see than the result isn't LTE only.

![Modem](https://user-images.githubusercontent.com/67963661/108332427-125aaa00-71d0-11eb-9653-a3eb51ad91aa.jpg)

**Comment by lewisxhe** [comment]
These two modules are just the difference in the generation date, there is no difference in function.
