### ISSUE TITLE
Excessive power draw

### ISSUE THREAD

**Issue by kapitan-u** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#8]
100k/100k divider for measuring battery power is causing excessive power draw.
please consider P-FET solution described here
https://fettricks.blogspot.com/2014/01/reducing-voltage-divider-load-to-extend.html
for future versions

**Comment by lewisxhe** [comment]
OK, I will advise the engineer.

**Comment by ClemensGruber** [comment]
... or use resistors with higher values.

**Comment by Mr-HaleYa** [comment]
@kapitan-u A new version of the board has been released (20200415) and P-Fets have been implemented throughout
---
If your issue has been solved please close
