### ISSUE TITLE
At command not responding

### ISSUE THREAD

**Issue by 4gino** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#83]
Hi, I' m trying to search for providers using at+cops? But  I end with errorr, and I cannot choose or change provider, It connects to the wrong and weakest, but cannot choose an alternative one. Can you please help. Thanks, i have other simcom modules and menage to control them, but not the one on the lilygo board.

**Comment by 4gino** [comment]
I mean At+cops=?  ...error

**Comment by 4gino** [comment]
At+csq give good signal, i tried different sketches, at debug, network test, etc. But when i send at+cops=? The serial monitor stops responding, the only way Is manual reset

**Comment by WRedux** [comment]
You've waited?
It took about 15sec. in my Case!
Then it responds with all available Providers...

**Comment by 4gino** [comment]
Waited minutes

**Comment by WRedux** [comment]
Tried CSQ?
Got 15,99

**Comment by procopio** [comment]
In the beginning I also tried at+cops=? and the same happened to me. 
I figured out how to live without this command.

**Comment by WRedux** [comment]
Have you Guys tried a Modem-Reset?
Could happen, if you mess up with AT-Commands...


LilyGO-T-SIM7000G/examples/Arduino_TinyGSM/ResetModem/
