### ISSUE TITLE
Hx711 wiring connection problem

### ISSUE THREAD

**Issue by 4gino** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#84]
Hi, please help, i'm trying to connect an hx711 but the only thing i can read is a one wire temperature sensor. When i connect the hx711 i get no device found using the code from here 
https://github.com/Xinyuan-LilyGO/TTGO-T-Display/issues/53
I now that probably there is a simple solution, but i'm enough frustrated. Thanks a lot.

**Comment by lewisxhe** [comment]
already responded
