### ISSUE TITLE
Download firmware 1529b05sim7000g

### ISSUE THREAD

**Issue by rakaandro** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#86]
[Documentation](https://github.com/Xinyuan-LilyGO/LilyGO-T-SIM7000G/blob/master/docs/How%20to%20update%20firmware.md
)

Hello, the link to download firmware for SIM7000G "1529b05sim7000g" is dead. Can you fix it, thanks!

Your dead One Drive Link:
https://1drv.ms/u/s!AmbpOqVezk5drSysFSgYu6bGRKy3?e=al2Ioh

**Comment by lewisxhe** [comment]
Please try this link 
https://1drv.ms/u/s!AmbpOqVezk5drSmGqHKQmMv23MPq?e=5FdDy6

**Comment by rakaandro** [comment]
Thanks, problems solved. Please change the [documentation](https://github.com/Xinyuan-LilyGO/LilyGO-T-SIM7000G/blob/master/docs/How%20to%20update%20firmware.md), too.
