### ISSUE TITLE
Power Supervision IC DIO6809S

### ISSUE THREAD

**Issue by kapitan-u** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#9]
Please consides including in future versions Power Supervision IC DIO6809S
http://www.dioo.com/uploads/product/20190312/eed546a7a6148e82e3d785879360556a.pdf

**Comment by lewisxhe** [comment]
OK, I will advise the engineer.

**Comment by Mr-HaleYa** [comment]
@kapitan-u
A new version of the board has been released (20200415) Please look at the new schematic then make new suggestions as feedback is always welcome

---
If your issue has been solved please close

**Comment by lewisxhe** [comment]
The new version has been updated, the issue will be closed, if there are other issues, please open the issue
