### ISSUE TITLE
Li-ion battery pack connection doubt

### ISSUE THREAD

**Issue by ishdemon** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#94]
where should i connect an external battery (Not 18650)? should i solder it to the + & - of the battery holder (Back side) and will it get charged normally also?

**Comment by ishdemon** [comment]
also charging is only done when USB is connected or it will also charge when i supply power via 5v & GND Pins??

**Comment by lewisxhe** [comment]
That’s right. You can only solder + and-on the back. You can’t connect it directly to 5V. It’s a voltage of 5V. If you connect it directly, it will be damaged.

**Comment by ishdemon** [comment]
no i meant external power supply on 5v & GND pins. Will this charge the battery connected.?

**Comment by lewisxhe** [comment]
@ishdemon Yes,it can be chargeing

**Comment by Mr-HaleYa** [comment]
@lewisxhe @ishdemon Your question was answered. close this or ask another one
